using JavaOpsin = uk.ac.cam.ch.wwmm.opsin;

namespace Opsin
{
    /// <summary>
    /// The type of problem OPSIN encountered
    /// </summary>
    public enum OpsinWarningType
    {
        /// <summary>
        /// OPSIN ignored stereochemistry from the input name to give this structure.
        /// </summary>
        /// <remarks>
        /// This can have various causes:
        /// <list type="bullet">
        /// <item>
        /// OPSIN doesn't support interpretation of the type of stereochemistry
        /// </item>
        /// <item>
        /// OPSIN stereo-perception doesn't support this type of stereocentre
        /// </item>
        /// <item>
        /// The name describes the wrong structure
        /// </item>
        /// <item>
        /// The stereochemistry is being requested at the wrong atom/bond
        /// </item>
        /// </list>
        /// </remarks>
        StereochemistryIgnored = 0,

        /// <summary>
        /// OPSIN made a choice that appeared to be ambiguous to give this structure i.e. the name may describe multiple possible structures
        /// </summary>
        /// <remarks>
        /// <list type="bullet">
        /// <item>The name may be missing locants</item>
        /// <item>Alternatively the name could actually be a trivial rather than systematic name</item>
        /// </list>
        /// OPSIN tries to make sensible choices when choosing in ambiguous cases so the resultant structure may nonetheless be the intended one
        /// </remarks>
        AppearsAmbiguous = 1,
    }

    /// <summary>
    /// A warning generated by OPSIN while interpreting a name.
    /// </summary>
    /// <remarks>
    /// The specifics of the warning may be used to judge whether you want to accept the generated structure.
    /// </remarks>
    public class OpsinWarning
    {
        private readonly JavaOpsin::OpsinWarning _o;

        internal OpsinWarning(JavaOpsin::OpsinWarning o)
        {
            _o = o;
        }

        /// <summary>
        /// The message describing the specific cause of this warning
        /// </summary>
        public string Message => _o.getMessage();

        /// <summary>
        /// The type of the warning.
        /// </summary>
        /// <seealso cref="OpsinWarningType"/>
        public OpsinWarningType WarningType => (OpsinWarningType)_o.getType().ordinal();
    }
}
